/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include	"STD_TYPES.h"
#include	"BIT_MATH.h"
#include    "Delay.h"

#include	"RCC_interface.h"
#include	"DIO_int.h"
#include    "LCD_int.h"



int	main(void)
{
	/*	Initialization Part		*/

	/*	System Clk init			*/
	MRCC_voidSysClkInit();


	/*	Toggle Led C13	GPIOC	*/
	/*	1- Enable Per Clk "RCC" Port A		*/
	MRCC_voidEnablePerClk(RCC_APB2,2);

	//LCD INITIALIZE
	H_LCD_void_Init();



	while(1)
	{
		 H_LCD_void_sendData('5');
      _delay_ms(500);
      H_LCD_void_clear();
      H_LCD_void_gotXY(1, 0);
      H_LCD_void_sendString("HI MR MUHSEN");
      _delay_ms(1000);
      H_LCD_void_clear();
      H_LCD_void_sendIntNum(1234);
      _delay_ms(500);
      H_LCD_void_clear();
	}
	return 0;
}


